### ISSUE TITLE
[FEAT] 회원가입 기능 추가

### ISSUE THREAD

**Issue by hamo-o** [Qfeed-Dev/qfeed-client-web#84]
## Description
기존 회원가입 기능 추가 및 이슈를 수정합니다.

## To-do
- [ ] 확대 방지를 위한 input 폰트 조정건 >> UI 정확하게 일치시키기
- [ ] 뒤로가기 불가 이슈
- [ ] 학교 API 연결
